### ISSUE TITLE
What do we use for Solar Time?

### ISSUE THREAD

**Issue by felixchan** [mbostock/solar-calculator#3]
Pardon the noob question. Given longitude, how can I get the real solar time?

**Comment by lulunac27a** [comment]
Solar time is based on Earth rotation relative to the sun. The formula is relative to solar noon time and solar time is calculated from local time plus 4 minutes per degree of longitude minus 1 hour per time zone in hours plus equation of time based on chosen date and time.

**Comment by felixchan** [comment]
Thank you!
